### ISSUE TITLE
Copy-Paste issues

### ISSUE THREAD

**Issue by codegeek182** [LibVNC/x11vnc#87]
Hi,

I suspect there's a bug in x11vnc in transferring data when pasting text to a session.
My knowledge in x11vnc is not deep enough so if you can please help me in this issue it will be really helpful.
I'm using x11vnc in order to view a rdp session with xfreerdp.
For some unknown reason I can't paste text from the host machine into the session.
When I try to simply copy and paste text from the machine into it self, it works well. I used python 2 on Ubuntu 18.04, ran gtk.wait_for_targets() and pasted inside the machine I received the wanted result - all the possible types (such as text/plain, STRING, TEXT, UTF8_STRING…):
Import gtk
a = gtk.clipboard_get()
a.wait_for_targets()

But when I connect to the machine with x11vnc, and then paste, and run gtk.wait_for_targets() I get None as a result.
Do you have an idea what can cause it?

Thanks,
Tomer

**Comment by bk138** [comment]
I'm having trouble understanding the basic setup :-) It's you -> vnc viewer -> x11vnc ?? xfreerdp?

**Comment by codegeek182** [comment]
I'm using the JavaScript library NoVNC as a viewer, x11vnc which acts as a vnc server against Xvfb  display which runs in the background, and xfreerdp which is running in the xvfb and acting as a client to a remote machine (it is basically a web-RDP gateway)

**Comment by oreaba** [comment]
I am having the same issue. I can copy from server to client but I can not copy from client to the x11vnc server.

**Comment by meramsey** [comment]
Can confirm if i start server on remote system Ubuntu 20.04 as `ubuntu` user
```
/usr/bin/x11vnc -listen localhost -listenv6 '::1' -display $DISPLAY -rfbport 5900 -forever -debug_sel &
```

I then inside the session copy text and can paste inside without issues. I can also copy from inside the session to out. I just cannot paste into the session from outside it always fails even though it looks like its updating it correctly based on the logs.


But if i try to paste from outside of session into it pyclip/pyperclip when trying to get the data from clipboard after updated externally seems to think its malformatted or empty.
```
(006190) [19:31:19] getClipboardData: Exception with pyclip: 'utf-8' codec can't decode byte 0xfd in position 0: invalid start byte
```



In debugging the output it looks like it is sending it 
```
21/12/2023 19:30:54 request CLIPBOARD
21/12/2023 19:30:54 selection_send: event CLIPBOARD prop: 31  requestor: 0x200014 atom: 243
selection_send: data: 'https://www.google.com/' dlen: 23 nitems: 23 ba: 0
21/12/2023 19:30:54 selection_send:  CLIPBOARD 'https://www.google.com/'
21/12/2023 19:30:54 selection_send:  no change.
21/12/2023 19:30:56 request CLIPBOARD
21/12/2023 19:30:56 selection_send: event CLIPBOARD prop: 31  requestor: 0x200014 atom: 243
selection_send: data: 'https://www.google.com/' dlen: 23 nitems: 23 ba: 0
21/12/2023 19:30:56 selection_send:  CLIPBOARD 'https://www.google.com/'
21/12/2023 19:30:56 selection_send:  no change.
21/12/2023 19:30:58 request CLIPBOARD
21/12/2023 19:30:58 selection_send: event CLIPBOARD prop: 31  requestor: 0x200014 atom: 243
selection_send: data: 'https://www.google.com/' dlen: 23 nitems: 23 ba: 0
21/12/2023 19:30:58 selection_send:  CLIPBOARD 'https://www.google.com/'
21/12/2023 19:30:58 selection_send:  no change.
21/12/2023 19:30:59 xcut_receive: 'https://www.google.com/'
21/12/2023 19:30:59 xcut_receive: recv-ing it.
21/12/2023 19:30:59 Own PRIMARY.
21/12/2023 19:30:59 Own CLIPBOARD.
21/12/2023 19:30:59 Set PRIMARY   'https://www.google.com/'
21/12/2023 19:30:59 Set CLIPBOARD 'https://www.google.com/'
21/12/2023 19:31:19 CLIPBOARD	request event:   owner=0x200014 requestor=0xe00001 sel=243 targ=253 prop=254
21/12/2023 19:31:19 TARGETS: XChangeProperty() -> 1 -- sz1: 8  sz2: 2
21/12/2023 19:31:19 XSendEvent() -> 1
21/12/2023 19:31:19 CLIPBOARD	request event:   owner=0x200014 requestor=0xe00001 sel=243 targ=253 prop=254
21/12/2023 19:31:19 TARGETS: XChangeProperty() -> 1 -- sz1: 8  sz2: 2
21/12/2023 19:31:19 XSendEvent() -> 1
21/12/2023 19:31:19 CLIPBOARD	request event:   owner=0x200014 requestor=0xe00001 sel=243 targ=253 prop=254
21/12/2023 19:31:19 TARGETS: XChangeProperty() -> 1 -- sz1: 8  sz2: 2
21/12/2023 19:31:19 XSendEvent() -> 1
21/12/2023 19:31:38 CLIPBOARD	request event:   owner=0x200014 requestor=0xe00001 sel=243 targ=253 prop=254
21/12/2023 19:31:38 TARGETS: XChangeProperty() -> 1 -- sz1: 8  sz2: 2
21/12/2023 19:31:38 XSendEvent() -> 1

```


based on the end parts from when it seems to have issues it looks like this bug?
https://www.linuxquestions.org/questions/linux-software-2/x11vnc-and-vncviewer-clipboard-transfter-548488/

**Comment by elirag** [comment]
should be fixed by https://github.com/LibVNC/x11vnc/pull/255

**Comment by tycho-kirchner** [comment]
@elirag Thanks for the PR. I tried the patch, but for me I still can't copy from client to server (the other way works). I'm using xtigervncviewer tunneled through ssh in `-listen` mode, both systems run Xfce under Debian Bookworm:
~~~
xtigervncviewer -listen $vnc_port &
sleep 1
# -noxdamage s. https://github.com/LibVNC/x11vnc/issues/154
# -auth guess
ssh -T -o ConnectTimeout=12 -R $vnc_port:localhost:$vnc_port \
      "DISPLAY=:0 x11vnc -q -clear_keys -noxdamage -repeat -nopw -connect_or_exit localhost:$vnc_port"
~~~

**Comment by Neustradamus** [comment]
@elirag: Have you seen the @tycho-kirchner comment?

@codegeek182, @oreaba: Have you tried the @elirag PR?
- https://github.com/LibVNC/x11vnc/pull/255
